# Generated by Django 4.2.6 on 2023-10-28 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import weapondetectapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=weapondetectapp.models.images_directory_path)),
                ('name', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=weapondetectapp.models.videos_directory_path)),
                ('name', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='VideoPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_predict', models.FileField(upload_to=weapondetectapp.models.videos_predict_directory_path)),
                ('boxes', models.JSONField(default=list)),
                ('video_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_original', to='weapondetectapp.video')),
            ],
            options={
                'verbose_name': 'Video Predict',
                'verbose_name_plural': 'Videos Predict',
            },
        ),
        migrations.CreateModel(
            name='ImagePredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_predict', models.ImageField(upload_to=weapondetectapp.models.images_predict_directory_path)),
                ('boxes', models.JSONField(default=list)),
                ('image_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_original', to='weapondetectapp.image')),
            ],
            options={
                'verbose_name': 'Image Predict',
                'verbose_name_plural': 'Images Predict',
            },
        ),
    ]
