# Generated by Django 4.2.6 on 2023-10-28 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import weapondetectapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weapondetectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=weapondetectapp.models.videos_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='ImagePredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_predict', models.ImageField(upload_to=weapondetectapp.models.images_directory_path)),
                ('boxes', models.JSONField(default=list)),
                ('image_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_original', to='weapondetectapp.image')),
            ],
            options={
                'verbose_name': 'Image Predict',
                'verbose_name_plural': 'Images Predict',
            },
        ),
    ]
