# Generated by Django 4.2.6 on 2023-10-28 20:19

from django.db import migrations, models
import weapondetectapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('weapondetectapp', '0002_image_name_video_imagepredict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepredict',
            name='image_predict',
            field=models.ImageField(upload_to=weapondetectapp.models.images_predict_directory_path),
        ),
    ]
